FROM jenkins/jenkins:lts

RUN jenkins-plugin-cli --plugins "git workflow-aggregator pipeline-stage-view"

USER root
RUN apt-get update && apt-get install -y \
    python3 \
    python3-venv \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

USER jenkins
COPY init.groovy /usr/share/jenkins/ref/init.groovy.d/init.groovy
