sonar.projectKey=aceest-fitness-gym
sonar.projectName=ACEest Fitness Gym
sonar.projectVersion=1.0
sonar.sources=aceest_app,app.py
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
