apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-app-canary
  labels:
    app: aceest-app
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aceest-app
      track: canary
  template:
    metadata:
      labels:
        app: aceest-app
        track: canary
    spec:
      containers:
        - name: aceest-app
          image: naveen1312/aceest-app:latest
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
