apiVersion: v1
kind: Service
metadata:
  name: aceest-app-bluegreen-service
spec:
  type: NodePort
  selector:
    app: aceest-app
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
